### ISSUE TITLE
Could not find location

### ISSUE THREAD

**Issue by RichardLitt** [watson/geopkg#9]
Not sure why. No VPN is on.  Mac OSX 10.12 Sierra. geopkg v4.0.3

```
Error: Geocoding service returned unexpected status code: 404
    at IncomingMessage.<anonymous> (/Users/richard/.nvm/versions/node/v8.1.2/lib/node_modules/geopkg/node_modules/geocode-wifi/index.js:40:44)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

**Comment by watson** [comment]
Yeah 😞 I also just got another issue on the matter: https://github.com/watson/wifi-triangulate/issues/4

I've been getting that too. Apparently Google removed the free API I was using. I've been trying to find an alternative all week, but so far no luck 😢

Any help would be much appreciated!
